name: 'Uncrustify C# Code Formatting'
description: 'Runs C# code format with Uncrustify'
author: 'mibmo'
inputs: 
  configPath:
    description: 'Alternate configuration file to use'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
    icon: 'edit-3'
    color: 'green'
